version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3.10 manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/ormal
    ports:
      - "8002:8002"